/**
 * ZINGO — In-Browser Automated Test Verification Engine
 * =====================================================
 * Executes Tree-of-Thought (ToT) test specifications generated by Node 2
 * against virtual project implementations directly inside the browser realm.
 */

export interface TestCase {
  name: string
  assertion_code: string
}

export interface TestCaseResult {
  name: string
  status: 'passed' | 'failed'
  durationMs: number
  error?: string
}

export interface TestRunResult {
  total: number
  passed: number
  failed: number
  durationMs: number
  cases: TestCaseResult[]
}

export class ClientTestRunner {
  /**
   * Executes a list of test cases against JavaScript/HTML/Python code.
   */
  public async runTests(
    projectFiles: Record<string, string>,
    testCases: TestCase[]
  ): Promise<TestRunResult> {
    const start = performance.now()
    const results: TestCaseResult[] = []

    // Collect JS/TS scripts from project
    const jsSource = Object.entries(projectFiles)
      .filter(([path]) => path.endsWith('.js') || path.endsWith('.ts'))
      .map(([_, content]) => content)
      .join('\n\n')

    for (const tc of testCases) {
      const tcStart = performance.now()
      try {
        // Build test runner harness
        const harness = `
          let __passed = true;
          let __err = null;
          function expect(actual) {
            return {
              toBe: (expected) => {
                if (actual !== expected) throw new Error("Expected " + JSON.stringify(expected) + " but received " + JSON.stringify(actual));
              },
              toEqual: (expected) => {
                if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error("Expected " + JSON.stringify(expected) + " but received " + JSON.stringify(actual));
              },
              toBeTruthy: () => {
                if (!actual) throw new Error("Expected truthy but received " + actual);
              },
              toBeFalsy: () => {
                if (actual) throw new Error("Expected falsy but received " + actual);
              },
              toBeGreaterThan: (val) => {
                if (actual <= val) throw new Error("Expected " + actual + " > " + val);
              },
              toBeLessThan: (val) => {
                if (actual >= val) throw new Error("Expected " + actual + " < " + val);
              }
            };
          }

          try {
            ${jsSource}
            ${tc.assertion_code}
          } catch(e) {
            __passed = false;
            __err = e.message || String(e);
          }
          return { passed: __passed, err: __err };
        `

        const testFn = new Function(harness)
        const outcome = testFn()

        const elapsed = Math.round(performance.now() - tcStart)
        if (outcome.passed) {
          results.push({
            name: tc.name,
            status: 'passed',
            durationMs: elapsed,
          })
        } else {
          results.push({
            name: tc.name,
            status: 'failed',
            durationMs: elapsed,
            error: outcome.err || 'Assertion failed',
          })
        }
      } catch (err: any) {
        const elapsed = Math.round(performance.now() - tcStart)
        results.push({
          name: tc.name,
          status: 'failed',
          durationMs: elapsed,
          error: err?.message || String(err),
        })
      }
    }

    const totalElapsed = Math.round(performance.now() - start)
    const passedCount = results.filter((r) => r.status === 'passed').length

    return {
      total: testCases.length,
      passed: passedCount,
      failed: testCases.length - passedCount,
      durationMs: totalElapsed,
      cases: results,
    }
  }
}

export const clientTestRunner = new ClientTestRunner()
